filebeat.inputs:
- type: log
  paths:
    - /var/log/httpd/one/*.log
    - /var/log/httpd/zero/*.log
  ignore_older: 3h

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch-service:9200"]

setup.kibana:
  host: "kibana-service:5601"